# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    build:
      html:
        - python -m mkdocs build --clean --site-dir $READTHEDOCS_OUTPUT/html --config-file mkdocs.yml 
        - python -m mkdocs build --clean --site-dir $READTHEDOCS_OUTPUT/html --config-file mkdocs.yml # Execute twice to make links to /images work
        - ls -la $READTHEDOCS_OUTPUT/html

python:
  install:
    - method: pip
      path: .
    - requirements: requirements-docs.txt

mkdocs:
  configuration: mkdocs.yml

formats: []
