# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_build:
      - cp -r docs/images $READTHEDOCS_OUTPUT/html

python:
  install:
    - method: pip
      path: .
    - requirements: requirements-docs.txt

mkdocs:
  configuration: mkdocs.yml

formats: []
