# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    build:
      - python -m mkdocs build --clean --site-dir $READTHEDOCS_OUTPUT/html --config-file mkdocs.yml 
      - cp -r docs/images $READTHEDOCS_OUTPUT/html

python:
  install:
    - method: pip
      path: .
    - requirements: requirements-docs.txt

mkdocs:
  configuration: mkdocs.yml

formats: 
  - htmlzip
