site_name: polygraph
theme:
  name: readthedocs  # Optional, but makes docs look better
  features:
    - navigation.expand  # Expands all sections by default
    - navigation.side.indexes

nav:
  - index.md
  - Installation: installation.md
  - Tutorials:
    - Basic Usage: tutorials/basic_usage.md
    - Loading Datasets: tutorials/datasets.md
    - Evaluating Models: tutorials/evaluating_models.md
    - Defining Custom Metrics: tutorials/custom_metrics.md
  - API Reference:
    - polygraph.metrics:
      - Interface: api_reference/metrics/interface.md
      - MMD: api_reference/metrics/mmd.md
      - PolyGraphScore: api_reference/metrics/polygraphscore.md
      - VUN: api_reference/metrics/vun.md
      - Frechet: api_reference/metrics/frechet.md
    - polygraph.datasets:
      - Dataset Base Classes: api_reference/datasets/dataset_base_classes.md
      - NetworkX View: api_reference/datasets/networkx_view.md
      - Graph Serialization: api_reference/datasets/graph_serialization.md
    - polygraph.utils:
      - Graph Descriptors: api_reference/utils/graph_descriptors.md
      - Graph Kernels: api_reference/utils/graph_kernels.md
  - Metrics:
    - GRAN: metrics/gran.md
    - GIN: metrics/gin.md
  - Datasets:
    - Small Synthetic Datasets: datasets/small_synthetic.md
    - Procedural Datasets: datasets/procedural.md
    - Real-World Datasets: datasets/real_world_topologies.md
    - Molecule Datasets: datasets/molecules.md
  - Utils:
    - Graph Descriptors: utils/descriptors.md
    - Graph Kernels: utils/kernels.md
    - MMD Utilities: utils/mmd_utils.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            extensions:
              - scripts/griffe_extension.py:JinjaDocstringExtension
      paths: [polygraph]

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true


extra_javascript:
  - javascript/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
