site_name: polygraph
theme:
  name: readthedocs  # Optional, but makes docs look better
  features:
    - navigation.expand  # Expands all sections by default
    - navigation.side.indexes

nav:
  - index.md
  - Installation: installation.md
  - Tutorials:
    - Loading Datasets: tutorials/datasets.md
    - Evaluating Models: tutorials/evaluating_models.md
    - Defining Custom Metrics: tutorials/custom_metrics.md
  - API Reference:
    - polygraph.metrics:
      - Base MMD Classes: api_reference/metrics/base_mmd.md
      - Other Base Metrics: api_reference/metrics/other_base.md
      - GRAN Metrics: api_reference/metrics/gran.md
      - GIN Metrics: api_reference/metrics/gin.md
    - polygraph.datasets:
      - Dataset Abstractions: api_reference/datasets/base.md
      - Small Synthetic Datasets: api_reference/datasets/small_synthetic.md
      - Procedural Datasets: api_reference/datasets/procedural.md
      - Real-World Datasets: api_reference/datasets/real_world_topologies.md
      - Molecule Datasets: api_reference/datasets/molecules.md
    - polygraph.utils:
      - Graph Descriptors: api_reference/utils/graph_descriptors.md
      - Graph Kernels: api_reference/utils/graph_kernels.md
      - MMD Utilities: api_reference/utils/mmd_utils.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            extensions:
              - scripts/griffe_extension.py:JinjaDocstringExtension
      paths: [polygraph]

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true


extra_javascript:
  - javascript/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
