[workspace]
name = "polygraph-benchmark"
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64"]

[dependencies]
python = "3.10.*"
graph-tool = "*"

[activation.env]
PYTHONPATH = "$PIXI_PROJECT_ROOT/reproducibility"

[pypi-dependencies]
polygraph-benchmark = { path = ".", editable = true, extras = ["dev", "cluster"] }

[tasks]
test = "pytest -n auto --dist loadgroup -v --tb=short --skip-slow ./tests"
test-all = "pytest -n auto --dist loadgroup -v --tb=short ./tests"
docs = "mkdocs build"
