[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "graph_gen_gym"
version = "0.1"
description = "Graph Generation Gym"
authors = [
    { name="Your Name", email="your.email@example.com" }
]
dependencies = [
    "numpy",
    "torch",
    "torch_geometric",
    "scipy",
    "pydantic",
    "networkx",
    "joblib",
    "appdirs",
    "loguru",
    "python-louvain",
    "orbit_count @ git+ssh://git@github.com/BorgwardtLab/orca-bindings.git"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-xdist",
    "hydra-core",
    "pyprojroot",
    "ipython",
    "ruff",
    "pre-commit",
    "pandas",
    "eden-kernel @ git+https://github.com/fabriziocosta/EDeN.git",      # Required for testing equivalence to Thompson et al.
    "torch>=2.4, <2.5",
    "dgl @ https://data.dgl.ai/wheels/torch-2.4/cu124/dgl-2.4.0%2Bcu124-cp310-cp310-manylinux1_x86_64.whl",
    "nvidia-cuda-runtime-cu12==12.4",
    "nvidia-cuda-nvrtc-cu12==12.4",
    "nvidia-cuda-cupti-cu12==12.4",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]

[tool.lint.ruff]
line-length = 80
target-version = "py312"
select = ["D"]
ignore = ["E731"]

[tool.lint.ruff.pydocstyle]
convention = "google"