[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "graph_gen_gym"
version = "0.1"
description = "Graph Generation Gym"
authors = [
    { name="Your Name", email="your.email@example.com" }
]
dependencies = [
    "numpy",
    "torch",
    "torch_geometric",
    "scipy",
    "pydantic",
    "networkx",
    "joblib",
    "appdirs",
    "loguru",
    "python-louvain",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-xdist",
    "hydra-core",
    "pyprojroot",
    "ipython",
    "ruff",
    "pre-commit"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-n auto -m 'not slow'"
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')"
]

[tool.lint.ruff]
line-length = 80
target-version = "py312"
select = ["D"]
ignore = ["E731"]

[tool.lint.ruff.pydocstyle]
convention = "google"