# Config for 06_mmd/compute.py
dataset: planar
model: AUTOGRAPH
subset: false

hydra:
  job:
    name: exp06_mmd
    chdir: false
  run:
    dir: logs/runs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: logs/sweeps/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  sweeper:
    params:
      dataset: planar,lobster,sbm,proteins
      model: AUTOGRAPH,DIGRESS,GRAN,ESGG
