name: Pyright Type Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Upgrade pip and install project (editable)
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Install Pyright
        run: |
          pip install pyright

      - name: Run Pyright
        run: |
          pyright --project pyproject.toml
